# Generated by Django 5.0.6 on 2024-05-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodid', models.AutoField(primary_key=True, serialize=False)),
                ('foodname', models.CharField(max_length=255)),
                ('foodunit', models.CharField(max_length=50)),
                ('foodcalo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dateofbirth', models.DateField()),
                ('currentweight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('recommendcalo', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('foodtotalcalo', models.IntegerField()),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaloTrackPro.food')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaloTrackPro.user')),
            ],
        ),
        migrations.CreateModel(
            name='CaloHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('datetotalcalo', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaloTrackPro.user')),
            ],
        ),
        migrations.CreateModel(
            name='WeightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaloTrackPro.user')),
            ],
        ),
    ]
